import { CardState } from "../../../types/cards/card_types";

const dragonBallImages = {
  goku: "/src/assets/cards/dragonBallImages/goku.jpg",
  krilin: "/src/assets/cards/dragonBallImages/krilin.jpg",
  vegeta: "/src/assets/cards/dragonBallImages/vegeta.jpg",
  gohan: "/src/assets/cards/dragonBallImages/gohan.jpg",
  picoro: "/src/assets/cards/dragonBallImages/picoro.jpg",
  trunks: "/src/assets/cards/dragonBallImages/trunks.jpg",
  bulma: "/src/assets/cards/dragonBallImages/bulma.jpg",
  roshi: "/src/assets/cards/dragonBallImages/roshi.jpg",
  background: "dragonBall",
};

export const drabonBallCards: CardState[] = [
  {
    id: "goku01",
    value: "goku",
    frontImg: dragonBallImages.goku,
    backImg: dragonBallImages.background,
    done: null,
    ViewFront: null,
  },
  {
    id: "goku02",
    value: "goku",
    frontImg: dragonBallImages.goku,
    backImg: dragonBallImages.background,
    done: null,
    ViewFront: null,
  },
  {
    id: "krilin01",
    value: "krilin",
    frontImg: "/src/assets/cards/dragonBallImages/krilin.jpg",
    backImg: dragonBallImages.background,
    done: null,
    ViewFront: null,
  },
  {
    id: "krilin02",
    value: "krilin",
    frontImg: "/src/assets/cards/dragonBallImages/krilin.jpg",
    backImg: dragonBallImages.background,
    done: null,
    ViewFront: null,
  },
  {
    id: "vegeta01",
    value: "vegeta",
    frontImg: "/src/assets/cards/dragonBallImages/vegeta.jpg",
    backImg: dragonBallImages.background,
    done: null,
    ViewFront: null,
  },
  {
    id: "vegeta02",
    value: "vegeta",
    frontImg: "/src/assets/cards/dragonBallImages/vegeta.jpg",
    backImg: dragonBallImages.background,
    done: null,
    ViewFront: null,
  },
  {
    id: "gohan01",
    value: "gohan",
    frontImg: "/src/assets/cards/dragonBallImages/gohan.jpg",
    backImg: dragonBallImages.background,
    done: null,
    ViewFront: null,
  },
  {
    id: "gohan02",
    value: "gohan",
    frontImg: "/src/assets/cards/dragonBallImages/gohan.jpg",
    backImg: dragonBallImages.background,
    done: null,
    ViewFront: null,
  },
  {
    id: "picoro01",
    value: "picoro",
    frontImg: "/src/assets/cards/dragonBallImages/picoro.jpg",
    backImg: dragonBallImages.background,
    done: null,
    ViewFront: null,
  },
  {
    id: "picoro02",
    value: "picoro",
    frontImg: "/src/assets/cards/dragonBallImages/picoro.jpg",
    backImg: dragonBallImages.background,
    done: null,
    ViewFront: null,
  },
  {
    id: "trunks01",
    value: "trunks",
    frontImg: "/src/assets/cards/dragonBallImages/trunks.jpg",
    backImg: dragonBallImages.background,
    done: null,
    ViewFront: null,
  },
  {
    id: "trunks02",
    value: "trunks",
    frontImg: "/src/assets/cards/dragonBallImages/trunks.jpg",
    backImg: dragonBallImages.background,
    done: null,
    ViewFront: null,
  },
  {
    id: "bulma01",
    value: "bulma",
    frontImg: "/src/assets/cards/dragonBallImages/bulma.jpg",
    backImg: dragonBallImages.background,
    done: null,
    ViewFront: null,
  },
  {
    id: "bulma02",
    value: "bulma",
    frontImg: "/src/assets/cards/dragonBallImages/bulma.jpg",
    backImg: dragonBallImages.background,
    done: null,
    ViewFront: null,
  },
  {
    id: "roshi01",
    value: "roshi",
    frontImg: "/src/assets/cards/dragonBallImages/roshi.jpg",
    backImg: dragonBallImages.background,
    done: null,
    ViewFront: null,
  },
  {
    id: "roshi02",
    value: "roshi",
    frontImg: "/src/assets/cards/dragonBallImages/roshi.jpg",
    backImg: dragonBallImages.background,
    done: null,
    ViewFront: null,
  },
];
