import { CardState } from "../../../types/cards/card_types";

const pokemonImages = {
  pikachu: "img/pikachu.jpg",
  charmandar: "img/charmander.jpg",
  mew: "img/mew.jpg",
  onix: "img/onix.jpg",
  snorlax: "img/snorlax.jpg",
  ditto: "img/ditto.jpg",
  squirtle: "img/squirtle.jpg",
  bulbasaur: "img/bulbasaur.jpg",
  background: "pokemon",
};

export const pokemonCards: CardState[] = [
  {
    id: "pikachu01",
    value: "pikachu",
    frontImg: pokemonImages.pikachu,
    backImg: pokemonImages.background,
    done: null,
    ViewFront: null,
  },
  {
    id: "pikachu02",
    value: "pikachu",
    frontImg: pokemonImages.pikachu,
    backImg: pokemonImages.background,
    done: null,
    ViewFront: null,
  },
  {
    id: "charmander01",
    value: "charmander",
    frontImg: pokemonImages.charmandar,
    backImg: pokemonImages.background,
    done: null,
    ViewFront: null,
  },
  {
    id: "charmander02",
    value: "charmander",
    frontImg: pokemonImages.charmandar,
    backImg: pokemonImages.background,
    done: null,
    ViewFront: null,
  },
  {
    id: "mew01",
    value: "mew",
    frontImg: pokemonImages.mew,
    backImg: pokemonImages.background,
    done: null,
    ViewFront: null,
  },
  {
    id: "mew02",
    value: "mew",
    frontImg: pokemonImages.mew,
    backImg: pokemonImages.background,
    done: null,
    ViewFront: null,
  },
  {
    id: "onix01",
    value: "onix",
    frontImg: pokemonImages.onix,
    backImg: pokemonImages.background,
    done: null,
    ViewFront: null,
  },
  {
    id: "onix02",
    value: "onix",
    frontImg: pokemonImages.onix,
    backImg: pokemonImages.background,
    done: null,
    ViewFront: null,
  },
  {
    id: "snorlax01",
    value: "snorlax",
    frontImg: pokemonImages.snorlax,
    backImg: pokemonImages.background,
    done: null,
    ViewFront: null,
  },
  {
    id: "snorlax02",
    value: "snorlax",
    frontImg: pokemonImages.snorlax,
    backImg: pokemonImages.background,
    done: null,
    ViewFront: null,
  },
  {
    id: "ditto01",
    value: "ditto",
    frontImg: pokemonImages.ditto,
    backImg: pokemonImages.background,
    done: null,
    ViewFront: null,
  },
  {
    id: "ditto02",
    value: "ditto",
    frontImg: pokemonImages.ditto,
    backImg: pokemonImages.background,
    done: null,
    ViewFront: null,
  },
  {
    id: "squirtle01",
    value: "squirtle",
    frontImg: pokemonImages.squirtle,
    backImg: pokemonImages.background,
    done: null,
    ViewFront: null,
  },
  {
    id: "squirtle02",
    value: "squirtle",
    frontImg: pokemonImages.squirtle,
    backImg: pokemonImages.background,
    done: null,
    ViewFront: null,
  },
  {
    id: "bulbasaur01",
    value: "bulbasaur",
    frontImg: pokemonImages.bulbasaur,
    backImg: pokemonImages.background,
    done: null,
    ViewFront: null,
  },
  {
    id: "bulbasaur02",
    value: "bulbasaur",
    frontImg: pokemonImages.bulbasaur,
    backImg: pokemonImages.background,
    done: null,
    ViewFront: null,
  },
];
